spring:
  application:
    name: WalletAPI
  datasource:
    url: jdbc:h2:mem:dbtest
    driver-class-name: org.h2.Driver
    username: in2admin
    password: in2pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  security:
    user:
      name: in2test
      password: in2pass

server:
  port: 8083

in2:
  openapi:
    local-url: http://localhost:8083
    dev-url: https://walletapidev.in2.es

app:
  url:
    api: http://localhost:8083
    orion_context_broker: http://localhost:1026/ngsi-ld/v1/entities

