spring:
  datasource:
    url: jdbc:mysql://local-mysql:3306/domedb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: in2admin
    password: in2pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: in2test
      password: in2pass

server:
  port: 8083

in2:
  openapi:
    local-url: http://localhost:8083
    dev-url: https://walletapidev.in2.es

app:
  url:
    api: https://walletapidev.in2.es
    orion_context_broker: http://wallet-orion-ld:1026/ngsi-ld/v1/entities

# Logging configuration
logging:
  level:
    # Set the log level for the entire application
    root: INFO
    # Set log level for specific packages or classes
    es.in2.wallet.service: DEBUG
    es.in2.wallet.util: DEBUG
