version: "3.8"
services:

  # MySQL
  local-mysql:
    container_name: local-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: D83Wh$tb83D8
      MYSQL_DATABASE: domedb
      MYSQL_USER: in2admin
      MYSQL_PASSWORD: in2pass
    volumes:
#      - ./init:/docker-entrypoint-initdb.d
      - MYSQL_DATA:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      local_net:

  # Context Broker
  context-broker:
    container_name: context-broker
#    image: fiware/orion-ld:latest
    image: fiware/orion:latest
    command: "-dbhost context-broker-mongo"
    ports:
      - "1026:1026"
    links:
      - context-broker-mongo
    networks:
      - local_net

  # Context Broker MongoDB
  context-broker-mongo:
    container_name: context-broker-mongo
    image: mongo:4.4
    command: "--nojournal"
    volumes:
      - CONTEXT_BROKER:/data/db
      - CONTEXT_BROKER_DBCONFIG:/data/configdb
    networks:
      - local_net

  # HashiCorp Vault
  hashicorp-vault:
    container_name: hashicorp-vault
    image: vault:1.13.3
    command: server -dev -dev-root-token-id='qQKmX1tK4iYMCxa9M7OXCYt0mW/5IgbLtXn2e1a5?S39AYl6Ho?fDgRsNE3PB254W8azjhIO8XKGWMsOw9BqpBQjeQhw0Kx7RfRxZUBnQysDoM1wFdhw/ya-5j1iZHv?qxF-u-GILhoJLiz2cDVZCoYcxlFiZcK/-8HXIvtFeJC5gKWh-nmiIelbUIV2adZ62t13gh09td/!hSo5s2raof4p6WC=hV=cJmr7kJPzV3JXRMld=BKvUuqIIrw4avz/'  # Replace with your Vault token    # Specify environment variables for Vault (update with actual values)
    environment:
      - "VAULT_ADDR=http://172.18.0.4:8200"   # Custom IP for microservice-vault container
    ports:
      - "8200:8200"
    volumes:
      - VAULT_DATA:/vault/data  # Volume to store Vault's data
      - VAULT_CONFIG:/vault/config  # Volume to store Vault's configuration
      - VAULT_FILE:/vault/file
      - VAULT_LOGS:/vault/logs
    networks:
      local_net:

networks:
  local_net:
volumes:
  MYSQL_DATA:
  CONTEXT_BROKER:
  CONTEXT_BROKER_DBCONFIG:
  VAULT_DATA:
  VAULT_CONFIG:
  VAULT_FILE:
  VAULT_LOGS: