package es.in2.wallet.api.model.dto

import com.fasterxml.jackson.annotation.JsonProperty

data class TermsOfService(
    @JsonProperty("Content") val content: String = "This application is provided solely for testing purposes. By using this application, you agree to the following terms and conditions:",
    @JsonProperty("Disclaimer") val disclaimer: String = "Please note that by using this application, you agree to abide by these terms and conditions. If you do not agree with any of these terms, please refrain from using the application.",
    @JsonProperty("LastUpdated") val lastUpdated: String = "09-06-2023",
    @JsonProperty("Terms") val terms: List<String> = listOf(
        "This application is not intended for production use and should not be used to process any sensitive or confidential data.",
        "The application may contain bugs, errors, or other issues that could result in unexpected behavior. The user acknowledges and accepts the risks associated with using the application.",
        "The user understands that any data submitted or generated by the application during testing may be deleted or modified without notice.",
        "The application is provided \"as is\" without any warranties or guarantees of any kind. The developer and contributors of the application are not liable for any damages or losses resulting from the use of the application.",
        "The user agrees not to reverse engineer, decompile, or modify the application in any way.",
        "The user agrees to use the application in compliance with all applicable laws and regulations.",
        "The developer reserves the right to modify or terminate the application at any time without prior notice."
    )
)